In [8]:
import csv
import pandas as pd

In [9]:
# reading the CSV file 
csvFile = pd.read_csv("../data/travel_data.csv") 
  
# displaying the contents of the CSV file 
print(csvFile)

       Unnamed: 0         date  state_fips state_code  pop_stay_at_home  \
0               0  01-Jan-2019           1         AL           1028578
1               1  01-Jan-2019          33         NH            312645
2               2  01-Jan-2019          34         NJ           2244189
3               3  01-Jan-2019          35         NM            525761
4               4  01-Jan-2019          36         NY           5931873
...           ...          ...         ...        ...               ...
31045       31666  12-Sep-2020          13         GA           2531945
31046       31667  12-Sep-2020          36         NY           6579119
31047       31668  12-Sep-2020          44         RI            290914
31048       31669  12-Sep-2020           8         CO           1663763
31049       31670  12-Sep-2020          45         SC           1156132

       pop_not_stay_at_home     trips   trips_1  trips_1_3  trips_3_5  ...  \
0                   3844356  11968328   2792091    3151108    1604875  ...
1                   1039666   3705345    726417     970009     492350  ...
2                   6637104  26078674   7491874    6764617    3009746  ...
3                   1563262   6475422   1972284    1756894     795723  ...
4                  13550603  60957950  18317662   15401822    7187598  ...
...                     ...       ...       ...        ...        ...  ...
31045               7987530  30701584   6440848    7397919    3851558  ...
31046              12963090  64920430  17877099   16189164    7773281  ...
31047                766401   3312803    820947     905972     412754  ...
31048               4031801  18217634   4467696    4488973    2195504  ...
31049               3927995  14773703   3069904    3625437    1906659  ...

       trips_250_500  trips_500  year  month  day  month_abbr  month_year  \
0              27164      10047  2019      1    1         Jan    Jan-2019
1               3998       7602  2019      1    1         Jan    Jan-2019
2              28397      63784  2019      1    1         Jan    Jan-2019
3              19001      10138  2019      1    1         Jan    Jan-2019
4              72132     117561  2019      1    1         Jan    Jan-2019
...              ...        ...   ...    ...  ...         ...         ...
31045         105617      46734  2020      9   12         Sep    Sep-2020
31046          78363     102136  2020      9   12         Sep    Sep-2020
31047           3915       3734  2020      9   12         Sep    Sep-2020
31048          49767      53040  2020      9   12         Sep    Sep-2020
31049          42444      18312  2020      9   12         Sep    Sep-2020

                state   latitude   longitude
0             Alabama  32.806671  -86.791130
1       New Hampshire  43.452492  -71.563896
2          New Jersey  40.298904  -74.521011
3          New Mexico  34.840515 -106.248482
4            New York  42.165726  -74.948051
...               ...        ...         ...
31045         Georgia  33.040619  -83.643074
31046        New York  42.165726  -74.948051
31047    Rhode Island  41.680893  -71.511780
31048        Colorado  39.059811 -105.311104
31049  South Carolina  33.856892  -80.945007

[31050 rows x 25 columns]

In [11]:
data = csvFile
data = data.drop(['Unnamed: 0'],axis=1)
data

,date,state_fips,state_code,pop_stay_at_home,pop_not_stay_at_home,trips,trips_1,trips_1_3,trips_3_5,trips_5_10,...,trips_250_500,trips_500,year,month,day,month_abbr,month_year,state,latitude,longitude
0,01-Jan-2019,1,AL,1028578,3844356,11968328,2792091,3151108,1604875,1879113,...,27164,10047,2019,1,1,Jan,Jan-2019,Alabama,32.806671,-86.791130
1,01-Jan-2019,33,NH,312645,1039666,3705345,726417,970009,492350,582185,...,3998,7602,2019,1,1,Jan,Jan-2019,New Hampshire,43.452492,-71.563896
2,01-Jan-2019,34,NJ,2244189,6637104,26078674,7491874,6764617,3009746,3582118,...,28397,63784,2019,1,1,Jan,Jan-2019,New Jersey,40.298904,-74.521011
3,01-Jan-2019,35,NM,525761,1563262,6475422,1972284,1756894,795723,834525,...,19001,10138,2019,1,1,Jan,Jan-2019,New Mexico,34.840515,-106.248482
4,01-Jan-2019,36,NY,5931873,13550603,60957950,18317662,15401822,7187598,8789865,...,72132,117561,2019,1,1,Jan,Jan-2019,New York,42.165726,-74.948051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31045,12-Sep-2020,13,GA,2531945,7987530,30701584,6440848,7397919,3851558,5116353,...,105617,46734,2020,9,12,Sep,Sep-2020,Georgia,33.040619,-83.643074
31046,12-Sep-2020,36,NY,6579119,12963090,64920430,17877099,16189164,7773281,9805686,...,78363,102136,2020,9,12,Sep,Sep-2020,New York,42.165726,-74.948051
31047,12-Sep-2020,44,RI,290914,766401,3312803,820947,905972,412754,508141,...,3915,3734,2020,9,12,Sep,Sep-2020,Rhode Island,41.680893,-71.511780
31048,12-Sep-2020,8,CO,1663763,4031801,18217634,4467696,4488973,2195504,2746467,...,49767,53040,2020,9,12,Sep,Sep-2020,Colorado,39.059811,-105.311104
31049,12-Sep-2020,45,SC,1156132,3927995,14773703,3069904,3625437,1906659,2464632,...,42444,18312,2020,9,12,Sep,Sep-2020,South Carolina,33.856892,-80.945007

In [12]:
data.to_html
data

,date,state_fips,state_code,pop_stay_at_home,pop_not_stay_at_home,trips,trips_1,trips_1_3,trips_3_5,trips_5_10,...,trips_250_500,trips_500,year,month,day,month_abbr,month_year,state,latitude,longitude
0,01-Jan-2019,1,AL,1028578,3844356,11968328,2792091,3151108,1604875,1879113,...,27164,10047,2019,1,1,Jan,Jan-2019,Alabama,32.806671,-86.791130
1,01-Jan-2019,33,NH,312645,1039666,3705345,726417,970009,492350,582185,...,3998,7602,2019,1,1,Jan,Jan-2019,New Hampshire,43.452492,-71.563896
2,01-Jan-2019,34,NJ,2244189,6637104,26078674,7491874,6764617,3009746,3582118,...,28397,63784,2019,1,1,Jan,Jan-2019,New Jersey,40.298904,-74.521011
3,01-Jan-2019,35,NM,525761,1563262,6475422,1972284,1756894,795723,834525,...,19001,10138,2019,1,1,Jan,Jan-2019,New Mexico,34.840515,-106.248482
4,01-Jan-2019,36,NY,5931873,13550603,60957950,18317662,15401822,7187598,8789865,...,72132,117561,2019,1,1,Jan,Jan-2019,New York,42.165726,-74.948051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31045,12-Sep-2020,13,GA,2531945,7987530,30701584,6440848,7397919,3851558,5116353,...,105617,46734,2020,9,12,Sep,Sep-2020,Georgia,33.040619,-83.643074
31046,12-Sep-2020,36,NY,6579119,12963090,64920430,17877099,16189164,7773281,9805686,...,78363,102136,2020,9,12,Sep,Sep-2020,New York,42.165726,-74.948051
31047,12-Sep-2020,44,RI,290914,766401,3312803,820947,905972,412754,508141,...,3915,3734,2020,9,12,Sep,Sep-2020,Rhode Island,41.680893,-71.511780
31048,12-Sep-2020,8,CO,1663763,4031801,18217634,4467696,4488973,2195504,2746467,...,49767,53040,2020,9,12,Sep,Sep-2020,Colorado,39.059811,-105.311104
31049,12-Sep-2020,45,SC,1156132,3927995,14773703,3069904,3625437,1906659,2464632,...,42444,18312,2020,9,12,Sep,Sep-2020,South Carolina,33.856892,-80.945007

In [15]:
data.to_html(open('../templates/travel_table.html', 'w'))